/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Hoofdstuk15_8;

/**
 *
 * @author marjolein.vancelst
 */
public class FastFoodRestaurantGUI extends javax.swing.JFrame {

    /**
     * Creates new form FastFoodRestaurantGUI
     */
    public FastFoodRestaurantGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMenu = new javax.swing.ButtonGroup();
        buttonGroupFrieten = new javax.swing.ButtonGroup();
        buttonGroupDrinks = new javax.swing.ButtonGroup();
        buttonGroupDrinksize = new javax.swing.ButtonGroup();
        paneelMenu = new javax.swing.JPanel();
        menuDoubleCheese = new javax.swing.JRadioButton();
        menuKingBurger = new javax.swing.JRadioButton();
        menuFishburger = new javax.swing.JRadioButton();
        menuVegetarianBurger = new javax.swing.JRadioButton();
        menuChickenNuggets = new javax.swing.JRadioButton();
        menuCheesenHam = new javax.swing.JRadioButton();
        paneelFrieten = new javax.swing.JPanel();
        frietenSmall = new javax.swing.JRadioButton();
        frietenMedium = new javax.swing.JRadioButton();
        frietenLarge = new javax.swing.JRadioButton();
        paneelDrinks = new javax.swing.JPanel();
        drinksCoke = new javax.swing.JRadioButton();
        drinksFanta = new javax.swing.JRadioButton();
        drinksSprite = new javax.swing.JRadioButton();
        paneelDrinksize = new javax.swing.JPanel();
        drinksize30cl = new javax.swing.JRadioButton();
        drinksize40cl = new javax.swing.JRadioButton();
        drinksize50cl = new javax.swing.JRadioButton();
        paneelSausjes = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneelMenu.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu's (3,00€)"));

        menuDoubleCheese.setText("Double Cheese");

        menuKingBurger.setText("King Burger");

        menuFishburger.setText("Fishburger");

        menuVegetarianBurger.setText("Vegetarian Burger");
        menuVegetarianBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVegetarianBurgerActionPerformed(evt);
            }
        });

        menuChickenNuggets.setText("Chicken Nuggets");

        menuCheesenHam.setText("Cheese & Ham");
        menuCheesenHam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCheesenHamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneelMenuLayout = new javax.swing.GroupLayout(paneelMenu);
        paneelMenu.setLayout(paneelMenuLayout);
        paneelMenuLayout.setHorizontalGroup(
            paneelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneelMenuLayout.createSequentialGroup()
                .addGroup(paneelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuDoubleCheese)
                    .addComponent(menuKingBurger)
                    .addComponent(menuFishburger))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuVegetarianBurger)
                    .addComponent(menuChickenNuggets)
                    .addComponent(menuCheesenHam))
                .addGap(59, 59, 59))
        );
        paneelMenuLayout.setVerticalGroup(
            paneelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuDoubleCheese)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuKingBurger)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuFishburger)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(paneelMenuLayout.createSequentialGroup()
                .addComponent(menuVegetarianBurger)
                .addGap(3, 3, 3)
                .addComponent(menuChickenNuggets)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuCheesenHam)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        paneelFrieten.setBorder(javax.swing.BorderFactory.createTitledBorder("Frieten"));
        paneelFrieten.setName(""); // NOI18N

        buttonGroupFrieten.add(frietenSmall);
        frietenSmall.setText("Small (1,40€)");

        buttonGroupFrieten.add(frietenMedium);
        frietenMedium.setText("Medium (1,80€)");

        buttonGroupFrieten.add(frietenLarge);
        frietenLarge.setText("Large (2,20€)");

        javax.swing.GroupLayout paneelFrietenLayout = new javax.swing.GroupLayout(paneelFrieten);
        paneelFrieten.setLayout(paneelFrietenLayout);
        paneelFrietenLayout.setHorizontalGroup(
            paneelFrietenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneelFrietenLayout.createSequentialGroup()
                .addGroup(paneelFrietenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frietenSmall)
                    .addComponent(frietenMedium)
                    .addComponent(frietenLarge))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        paneelFrietenLayout.setVerticalGroup(
            paneelFrietenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneelFrietenLayout.createSequentialGroup()
                .addComponent(frietenSmall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frietenMedium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frietenLarge)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        paneelDrinks.setBorder(javax.swing.BorderFactory.createTitledBorder("Drinks"));

        buttonGroupDrinks.add(drinksCoke);
        drinksCoke.setText("Coke");

        buttonGroupDrinks.add(drinksFanta);
        drinksFanta.setText("Fanta");

        buttonGroupDrinks.add(drinksSprite);
        drinksSprite.setText("Sprite");

        javax.swing.GroupLayout paneelDrinksLayout = new javax.swing.GroupLayout(paneelDrinks);
        paneelDrinks.setLayout(paneelDrinksLayout);
        paneelDrinksLayout.setHorizontalGroup(
            paneelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneelDrinksLayout.createSequentialGroup()
                .addGroup(paneelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drinksCoke)
                    .addComponent(drinksFanta)
                    .addComponent(drinksSprite))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        paneelDrinksLayout.setVerticalGroup(
            paneelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneelDrinksLayout.createSequentialGroup()
                .addComponent(drinksCoke)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drinksFanta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drinksSprite)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        paneelDrinksize.setBorder(javax.swing.BorderFactory.createTitledBorder("Drinksize"));

        buttonGroupDrinksize.add(drinksize30cl);
        drinksize30cl.setText("30 cl (1,30€)");
        drinksize30cl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinksize30clActionPerformed(evt);
            }
        });

        buttonGroupDrinksize.add(drinksize40cl);
        drinksize40cl.setText("40 cl (1,70€)");
        drinksize40cl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinksize40clActionPerformed(evt);
            }
        });

        buttonGroupDrinksize.add(drinksize50cl);
        drinksize50cl.setText("50 cl (2,00€)");
        drinksize50cl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinksize50clActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneelDrinksizeLayout = new javax.swing.GroupLayout(paneelDrinksize);
        paneelDrinksize.setLayout(paneelDrinksizeLayout);
        paneelDrinksizeLayout.setHorizontalGroup(
            paneelDrinksizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneelDrinksizeLayout.createSequentialGroup()
                .addGroup(paneelDrinksizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drinksize30cl)
                    .addComponent(drinksize40cl)
                    .addComponent(drinksize50cl))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        paneelDrinksizeLayout.setVerticalGroup(
            paneelDrinksizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneelDrinksizeLayout.createSequentialGroup()
                .addComponent(drinksize30cl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drinksize40cl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drinksize50cl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneelSausjes.setBorder(javax.swing.BorderFactory.createTitledBorder("Sausjes (0,50€)"));

        javax.swing.GroupLayout paneelSausjesLayout = new javax.swing.GroupLayout(paneelSausjes);
        paneelSausjes.setLayout(paneelSausjesLayout);
        paneelSausjesLayout.setHorizontalGroup(
            paneelSausjesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        paneelSausjesLayout.setVerticalGroup(
            paneelSausjesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(paneelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneelSausjes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(paneelFrieten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(paneelDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(paneelDrinksize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(paneelDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(paneelDrinksize, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(paneelFrieten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paneelSausjes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void drinksize40clActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinksize40clActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drinksize40clActionPerformed

    private void drinksize50clActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinksize50clActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drinksize50clActionPerformed

    private void drinksize30clActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinksize30clActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drinksize30clActionPerformed

    private void menuVegetarianBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVegetarianBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuVegetarianBurgerActionPerformed

    private void menuCheesenHamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCheesenHamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCheesenHamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FastFoodRestaurantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FastFoodRestaurantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FastFoodRestaurantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FastFoodRestaurantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FastFoodRestaurantGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDrinks;
    private javax.swing.ButtonGroup buttonGroupDrinksize;
    private javax.swing.ButtonGroup buttonGroupFrieten;
    private javax.swing.ButtonGroup buttonGroupMenu;
    private javax.swing.JRadioButton drinksCoke;
    private javax.swing.JRadioButton drinksFanta;
    private javax.swing.JRadioButton drinksSprite;
    private javax.swing.JRadioButton drinksize30cl;
    private javax.swing.JRadioButton drinksize40cl;
    private javax.swing.JRadioButton drinksize50cl;
    private javax.swing.JRadioButton frietenLarge;
    private javax.swing.JRadioButton frietenMedium;
    private javax.swing.JRadioButton frietenSmall;
    private javax.swing.JRadioButton menuCheesenHam;
    private javax.swing.JRadioButton menuChickenNuggets;
    private javax.swing.JRadioButton menuDoubleCheese;
    private javax.swing.JRadioButton menuFishburger;
    private javax.swing.JRadioButton menuKingBurger;
    private javax.swing.JRadioButton menuVegetarianBurger;
    private javax.swing.JPanel paneelDrinks;
    private javax.swing.JPanel paneelDrinksize;
    private javax.swing.JPanel paneelFrieten;
    private javax.swing.JPanel paneelMenu;
    private javax.swing.JPanel paneelSausjes;
    // End of variables declaration//GEN-END:variables
}
